### ISSUE TITLE
Build rust open source list

### ISSUE THREAD

**Issue by stocks29** [gitgig-io/awesome-open-source#3]
Populate this page with projects: https://github.com/gitgig-io/awesome-open-source/blob/master/docs/rust.md

Must follow the [contributing guidelines](https://github.com/gitgig-io/awesome-open-source/?tab=readme-ov-file#contributing)

**Comment by SherbetLemon47** [comment]
Forgot to ask for assignment but added a PR!

**Comment by stocks29** [comment]
@SherbetLemon47 thanks for submitting the PRs. I'll be taking a look at these early this week.

**Comment by stocks29** [comment]
@SherbetLemon47 just wanted to mention that you don't need to manually claim the rewards for completed issues since your github identity is already linked up to your wallet via the GitGig NFT. the rewards are automatically sent to your linked wallet for all completed bounties going forward.

here are the issue pages which show the transactions if you want to confirm:

https://app.gitgig.io/bounties/18
https://app.gitgig.io/bounties/20
